language: minimal

#Indico que voy a hacer la integración probándolo en dos distribuciones de linux: focal, y xenial (por defecto suelen usar xenial).
jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: xenial
env:
  #probando interpolar variables
  - HOME_DIR: ${HOME}
#Ejecución de los test en docker container.
script:
  - ls $HOME_DIR
  - echo $TRAVIS_BUILD_DIR
  - docker run -t -v $TRAVIS_BUILD_DIR:/test ghcr.io/wolfye98/proyecto_iv_bate
