language: minimal
os:
  - linux
  - osx

#Indicamos que usaremos un servicio docker, para usar el contenedor después.
services:
  - docker
#Ejecución de los test en local y en docker container.
script:
  - docker run -t -v $TRAVIS_BUILD_DIR:/test wolfye98/proyecto_iv_bate
