language: minimal

jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: xenial
#Ejecución de los test en docker container.
script:
  - docker run -t -v $TRAVIS_BUILD_DIR:/test ghcr.io/wolfye98/proyecto_iv_bate
