#Indicamos que usaremos un servicio docker, para usar el contenedor después.
services:
  - docker
#Estas son las preinstalaciones, que traen la imagen de docker, instalan las dependencias e instala gulp.
before_install:
  - docker pull wolfye98/proyecto_iv_bate
#Ejecución de los test en local y en docker container.
script:
  - docker run -t -v `pwd`:/test wolfye98/proyecto_iv_bate
