language: minimal

#Indico que voy a hacer la integraci칩n prob치ndolo en dos distribuciones de linux: focal, y xenial (por defecto suelen usar xenial).
jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: xenial
#Defino una variable de entorno que tendr치 la ruta al directorio de trabajo
env:
  - HOME_DIR: ${HOME}/build/WolfYe98/Proyecto_IV_Bate
#Ejecuci칩n de los test en docker container.
script:
  - docker run -t -v $HOME_DIR:/test ghcr.io/wolfye98/proyecto_iv_bate
