name: Publish Docker image
on: [push]
jobs:
  push_to_registries:
    name: Push Docker image Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wolfye98/proyecto_iv_bate
          tag_with_ref: true
