name: Testing GHCR Image

on: [push]

jobs:
  check_file_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if files changed
        id: changed
        uses: jackton1/find-changed-files@v1.1
        with:
          files: "Dockerfile, package.json"

      - name: Build if file changed
        run: echo ${{ steps.changed.outputs.files_changed }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: docker run -t -v `pwd`:/test ghcr.io/wolfye98/proyecto_iv_bate
