name: Testing GHCR Image

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: docker run -t -v `pwd`:/test ghcr.io/wolfye98/proyecto_iv_bate
